module.exports.ADD_SERVER_ERROR = "ADD_SERVER_ERROR";
module.exports.NEW_SERVER_ADDED_SUCCESSFULLY = "NEW_SERVER_ADDED_SUCCESSFULLY";
module.exports.SERVER_REMOVE_ERROR = "SERVER_REMOVE_ERROR";
module.exports.SERVER_REMOVED_SUCCESSFULLY = "SERVER_REMOVED_SUCCESSFULLY";
module.exports.SERVERS_FETCHED_SUCCEFFULLY = "SERVERS_FETCH_SUCCESSFULL";
module.exports.SERVERS_FETCHED_ERROR = "SERVERS_FETCH_ERROR";
module.exports.SERVER_STATUS_UPDATED = "SERVER_STATUS_UPDATED";
module.exports.SERVER_STATUS_UPDATE_ERROR = "SERVER_STATUS_UPDATE_ERROR";

module.exports.BUNDLES_FETCHED_SUCCESSFULLY = "BUNDLES_FETCHED_SUCCESSFULLY";
module.exports.BUNDLES_FETCH_ERROR = "BUNDLES_FETCHED_ERROR";
module.exports.BUNDLE_STARTED_SUCCESSFULLY = "BUNDLES_STARTED_SUCCESSFULLY";
module.exports.BUNDLE_START_ERROR = "BUNDLES_START_ERROR";
module.exports.BUNDLE_STOPPED_SUCCESSFULLY = "BUNDLES_STOPPED_SUCCESSFULLY";
module.exports.BUNDLE_STOP_ERROR = "BUNDLES_STOP_ERROR";