module.exports.ADD_SERVER_ERROR = "ADD_SERVER_ERROR";
module.exports.NEW_SERVER_ADDED_SUCCESSFULLY = "NEW_SERVER_ADDED_SUCCESSFULLY";
module.exports.SERVER_REMOVE_ERROR = "SERVER_REMOVE_ERROR";
module.exports.SERVER_REMOVED_SUCCESSFULLY = "SERVER_REMOVED_SUCCESSFULLY";
module.exports.SERVERS_FETCHED_SUCCESSFULLY = "SERVERS_FETCHED_SUCCESSFULLY";
module.exports.SERVERS_FETCHED_ERROR = "SERVERS_FETCH_ERROR";
module.exports.SERVER_STATUS_UPDATED = "SERVER_STATUS_UPDATED";
module.exports.SERVER_STATUS_UPDATE_ERROR = "SERVER_STATUS_UPDATE_ERROR";

module.exports.BUNDLES_FETCHED_SUCCESSFULLY = "BUNDLES_FETCHED_SUCCESSFULLY";
module.exports.BUNDLES_FETCH_ERROR = "BUNDLES_FETCHED_ERROR";

//module.exports.BUNDLE_ACTION_SUCCESSFUL = "BUNDLE_ACTION_SUCCESSFUL";
//module.exports.BUNDLE_ACTION_ERROR = "BUNDLE_ACTION_ERROR";
//module.exports.BUNDLE_ACTION_PENDING = "BUNDLE_ACTION_PENDING";
//module.exports.COMPONENT_ACTION_SUCCESSFUL = "COMPONENT_ACTION_SUCCESSFUL";
//module.exports.COMPONENT_ACTION_ERROR = "COMPONENT_ACTION_ERROR";
//module.exports.COMPONENT_ACTION_PENDING = "COMPONENT_ACTION_PENDING";
module.exports.SEARCH_ITEM_ACTION_SUCCEED = "SEARCH_ITEM_ACTION_SUCCEED";
module.exports.SEARCH_ITEM_ACTION_FAILED = "SEARCH_ITEM_ACTION_FAILED";
module.exports.SEARCH_ITEM_ACTION_PENDING = "SEARCH_ITEM_ACTION_PENDING";